name: Consume Javascript action

on:
 issue_comment:
   types: [created]

jobs:
  run_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Uses Action
        id: get-joke
        uses: ./

      
      - name: create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue_number: $ {{ github.event.issue.number}}
          body: $ {{ steps.get-joke.outputs.joke}}
